### ISSUE TITLE
Demucs updated to v2

### ISSUE THREAD

**Issue by adefossez** [xserrat/docker-facebook-demucs#1]
Hi @xserrat,
I just updated demucs including the CLI flags. You should remove the --dl flag, which is no longer supported (it is always implied). Also you could replace the default model used (-n flag) from demucs to demucs_quantized which will be much smaller and equivalent quality.

I can send a PR tomorrow :)

**Comment by xserrat** [comment]
Hi @adefossez !

Thank you so much for the update :) Feel free to open the PR to apply these changes.

Thanks again!
