### ISSUE TITLE
`build` Makefile target is executed without cache causing entire build every time

### ISSUE THREAD

**Issue by xserrat** [xserrat/docker-facebook-demucs#30]
Does it build the docker image on _every_ `make run track=mysong.mp3` now or only when necessary (remote `facebook/demucs` branch is ahead of local branch), i.e. does it auto-check if building is necessary?
Building on every run seems not optimal to me either, because here at least it takes a good while to build (just did a `make build` as per your advice above before I saw your new post).

_Originally posted by @nofishonfriday in https://github.com/xserrat/docker-facebook-demucs/discussions/25#discussioncomment-4592465_

**Comment by nofishonfriday** [comment]
Thanks. :)
