### ISSUE TITLE
shifts option?

### ISSUE THREAD

**Issue by mdlaat** [xserrat/docker-facebook-demucs#34]
Thank you for your work.
Would it be possible to add the shifts option to your script?

**Comment by xserrat** [comment]
Hi @mdlaat , do you mean this option?
```
The --shifts=SHIFTS performs multiple predictions with random shifts (a.k.a the shift trick) of the input and average them. This makes prediction SHIFTS times slower. Don't use it unless you have a GPU.
```

**Comment by mdlaat** [comment]
Yes, that’s the one!

**Comment by chucknelson** [comment]
@mdlaat I can't find an explanation of what values are recommended for this. Do you know of any resources that explain when you'd want to use this option and what value(s) to use?

**Comment by mdlaat** [comment]
As I understand, one might get better results using shifts, at the costs of processingpower/time. 
Found this in the code: https://github.com/facebookresearch/demucs/blob/e976d93ecc3865e5757426930257e200846a520a/demucs/separate.py#L46

**Comment by mdlaat** [comment]
Please do. Learning how to create a PR is still on my todolist. Thank you so much!

**Comment by xserrat** [comment]
We can close this issue thanks to the @chucknelson contribution! Thank you so much both for adding more value to this project!
