### ISSUE TITLE
New Demucs release coming up

### ISSUE THREAD

**Issue by adefossez** [xserrat/docker-facebook-demucs#7]
Hello @xserrat , on the 12th of November I will release a new version of Demucs. This should only require minor command line changes :) I'll submit a PR soon but wanted to give you a heads up.

**Comment by xserrat** [comment]
Hi @adefossez ! I'm glad to see you here :-) 

It sounds really good, I'll keep an eye on your pull request 🚀 

Thank you for your contributions and for your work!!

**Comment by adefossez** [comment]
The release just happened. I think though that the docker file should still be compatible out of the box.

**Comment by jaolan** [comment]
@adefossez With the removal of the --models flag in Demucs v3, it is not compatible out of the box. This is because the Dockerfile stores the models in the /data/models Docker volume using the flag. 

I have cooked up a temp working version and will submit a PR in case it is of use to anyone =)

**Comment by xserrat** [comment]
Hi @adefossez , thank you so much for your concern regarding the compatibility. This is great news!! I'm going to try it as soon as possible and I let you know.

> The release just happened. I think though that the docker file should still be compatible out of the box.

Hi @jaolan , thanks for your contribution. Your pull requests are welcomed so feel free to submit them! :) I'm going to check this issue as well!

**Comment by xserrat** [comment]
> The release just happened. I think though that the docker file should still be compatible out of the box.

Hi @adefossez , thank you so much for your concern regarding the compatibility. This is great news!! I'm going to try it as soon as possible and I let you know.

**Comment by xserrat** [comment]
> @adefossez With the removal of the --models flag in Demucs v3, it is not compatible out of the box but it is a simple fix. This is because the Dockerfile stores the models in the /data/models Docker volume using the flag.
> 
> I have cooked up a temp working version and will submit a PR in case it is of use to anyone =)

Hi @jaolan , thanks for your contribution. Your pull requests are welcomed so feel free to submit them! :) I'm going to check this issue as well!

**Comment by loretoparisi** [comment]
Hey @xserrat with latest build I'm getting this error:

```
...
 => exporting to image                                                                                                                                           33.6s 
 => => exporting layers                                                                                                                                          33.6s 
 => => writing image sha256:f82cd9f65e54a9bdeeb2c29784c59380b774974334d42129c3d8aabe8f60a40f                                                                      0.0s 
 => => naming to docker.io/facebook/demucs:latest                                                                                                                 0.0s 
                                                                                                                                                                       
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
docker run --rm -i \
		--name=demucs \
		-v /Users/loretoparisi/Documents/Projects/demucs/input:/data/input \
		-v /Users/loretoparisi/Documents/Projects/demucs/output:/data/output \
		-v /Users/loretoparisi/Documents/Projects/demucs/models:/data/models \
		facebook/demucs:latest \
		"python3 -m demucs.separate --out /data/output --models /data/models \
		/data/input//root/audio/82929740.mp3"
usage: demucs.separate [-h] [-s SIG | -n NAME] [--repo REPO] [-v] [-o OUT]
                       [-d DEVICE] [--shifts SHIFTS] [--overlap OVERLAP]
                       [--no-split] [--mp3] [--mp3-bitrate MP3_BITRATE]
                       tracks [tracks ...]
demucs.separate: error: unrecognized arguments: --models
make: *** [run] Error 2
```

**Comment by adefossez** [comment]
Yes ! I think a simple fix is to replace prepend the Demucs command with "$TORCH_HOME=/data/models". I can make a pull request tomorrow.

**Comment by loretoparisi** [comment]
Sent a [PR](https://github.com/xserrat/docker-facebook-demucs/pull/11)!
